### ISSUE TITLE
create new worksheets?

### ISSUE THREAD

**Issue by vanlong441** [abetomo/node-ss2json#107]
after learning concepts from google-spreadsheet (another npm package), I've tried out yours and got amazed by how much more streamlined the workflow has now become. Kudos!

By the way, is there some way to create new worksheets?

**Comment by abetomo** [comment]
Thank you.
You can update an existing sheet, but you cannot create a new one.

Feature Additions:
Implement the creation of a new worksheet.

**Comment by abetomo** [comment]
Released. Please contact us if you have any questions.

**Comment by vanlong441** [comment]
```
node server.js
(node:7105) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at sheets.spreadsheets.values.batchUpdate (/home/vanlongpham/Documents/sheet/node_modules/ss2json/lib/google/sheets.js:46:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7105) UnhandledPromiseRejectionWarning: Error: Invalid data[0]: Unable to parse range: Student!A1:Z
    at Gaxios._request (/home/vanlongpham/Documents/sheet/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by abetomo** [comment]
Is the version you're using 3.1.0?

**Comment by vanlong441** [comment]
> Is the version you're using 3.1.0?

All is good now. I was using 3.0.8 the whole time :D

**Comment by abetomo** [comment]
That’s' great.
Please feel free to open the issue if you need anything.
